services:

  frontend:
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    stdin_open: true

  backend:
    build:
        dockerfile: ./Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules