services:

  frontend:
    build:
      dockerfile: ./Dockerfile.prod
    ports:
      - "8080:8080"
    restart: unless-stopped

  backend:
    build:
        dockerfile: ./Dockerfile.prod
    ports:
      - "5000:5000"
    restart: unless-stopped