version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    networks:
      - "mern-blog"

  backend:
    build:
      context: ./backend
    networks:
      - "mern-blog"

  mongo:
    image: mongo:4.4-bionic
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - "mern-blog"
      
networks:
    mern-blog:
      driver: bridge
      
volumes:
  mongo-data:
    driver: local
