const CREATE_POST__REQUEST = "CREATE_POST__REQUEST";
const CREATE_POST__SUCCESS = "CREATE_POST__SUCCESS";
const CREATE_POST__FAIL = "CREATE_POST__FAIL";

const GET_ALL_POSTS__REQUEST = "GET_ALL_POSTS__REQUEST";
const GET_ALL_POSTS__SUCCESS = "GET_ALL_POSTS__SUCCESS";
const GET_ALL_POSTS__FAIL = "GET_ALL_POSTS__FAIL";

const GET_MY_POSTS__REQUEST = "GET_MY_POSTS__REQUEST";
const GET_MY_POSTS__SUCCESS = "GET_MY_POSTS__SUCCESS";
const GET_MY_POSTS__FAIL = "GET_MY_POSTS__FAIL";

const GET_SINGLE_POST__REQUEST = "GET_SINGLE_POST__REQUEST";
const GET_SINGLE_POST__SUCCESS = "GET_SINGLE_POST__SUCCESS";
const GET_SINGLE_POST__FAIL = "GET_SINGLE_POST__FAIL";

const DELETE_POST__REQUEST = "DELETE_POST__REQUEST";
const DELETE_POST__SUCCESS = "DELETE_POST__SUCCESS";
const DELETE_POST__FAIL = "DELETE_POST__FAIL";


const CLEAR_MY_POSTS = "CLEAR_MY_POSTS";


const CLEAR__MESSAGES = "CLEAR__MESSAGES";
const CLEAR__ERRORS = "CLEAR__ERRORS";

export {
    CREATE_POST__REQUEST, CREATE_POST__SUCCESS, CREATE_POST__FAIL,
    GET_ALL_POSTS__REQUEST, GET_ALL_POSTS__SUCCESS, GET_ALL_POSTS__FAIL,
    GET_MY_POSTS__REQUEST, GET_MY_POSTS__SUCCESS, GET_MY_POSTS__FAIL,
    GET_SINGLE_POST__REQUEST, GET_SINGLE_POST__SUCCESS, GET_SINGLE_POST__FAIL,
    DELETE_POST__REQUEST, DELETE_POST__SUCCESS, DELETE_POST__FAIL,

    CLEAR_MY_POSTS,
    CLEAR__ERRORS, CLEAR__MESSAGES
};