const TEST_CONSTANT__REQUEST = "TEST_CONSTANT__REQUEST";
const TEST_CONSTANT__SUCCESS = "TEST_CONSTANT__SUCCESS";
const TEST_CONSTANT__FAIL = "TEST_CONSTANT__FAIL";

export { TEST_CONSTANT__REQUEST, TEST_CONSTANT__SUCCESS, TEST_CONSTANT__FAIL };