const REGISTER__REQUEST = "REGISTER__REQUEST";
const REGISTER__SUCCESS = "REGISTER__SUCCESS";
const REGISTER__FAIL = "REGISTER__FAIL";

const CHANGE_EMAIL_AT_VERIFICATION = "CHANGE_EMAIL_AT_VERIFICATION";

const REGISTERATION_VERIFICATION__REQUEST = "REGISTERATION_VERIFICATION__REQUEST";
const REGISTERATION_VERIFICATION__SUCCESS = "REGISTERATION_VERIFICATION__SUCCESS";
const REGISTERATION_VERIFICATION__FAIL = "REGISTERATION_VERIFICATION__FAIL";

const OTP_VERIFICATION_FAILURE__REQUEST = "OTP_VERIFICATION_FAILURE__REQUEST";
const OTP_VERIFICATION_FAILURE__SUCCESS = "OTP_VERIFICATION_FAILURE__SUCCESS";
const OTP_VERIFICATION_FAILURE__FAIL = "OTP_VERIFICATION_FAILURE__FAIL";

const RESEND_OTP__REQUEST = "RESEND_OTP__REQUEST";
const RESEND_OTP__SUCCESS = "RESEND_OTP__SUCCESS";
const RESEND_OTP__FAIL = "RESEND_OTP__FAIL";

const LOGIN__REQUEST = "LOGIN__REQUEST";
const LOGIN__SUCCESS = "LOGIN__SUCCESS";
const LOGIN__FAIL = "LOGIN__FAIL";

const FORGOT_PASSWORD__REQUEST = "FORGOT_PASSWORD__REQUEST";
const FORGOT_PASSWORD__SUCCESS = "FORGOT_PASSWORD__SUCCESS";
const FORGOT_PASSWORD__FAIL = "FORGOT_PASSWORD__FAIL";

const RESET_PASSWORD_VERIFICATION__REQUEST = "RESET_PASSWORD_VERIFICATION__REQUEST";
const RESET_PASSWORD_VERIFICATION__SUCCESS = "RESET_PASSWORD_VERIFICATION__SUCCESS";
const RESET_PASSWORD_VERIFICATION__FAIL = "RESET_PASSWORD_VERIFICATION__FAIL";

const RESET_PASSWORD_RESEND_OTP__REQUEST = "RESET_PASSWORD_RESEND_OTP__REQUEST";
const RESET_PASSWORD_RESEND_OTP__SUCCESS = "RESET_PASSWORD_RESEND_OTP__SUCCESS";
const RESET_PASSWORD_RESEND_OTP__FAIL = "RESET_PASSWORD_RESEND_OTP__FAIL";

const LOGOUT__REQUEST = "LOGOUT__REQUEST";
const LOGOUT__SUCCESS = "LOGOUT__SUCCESS";
const LOGOUT__FAIL = "LOGOUT__FAIL";

const CHECK_USER_STATUS__REQUEST = "CHECK_USER_STATUS__REQUEST";
const CHECK_USER_STATUS__SUCCESS = "CHECK_USER_STATUS__SUCCESS";
const CHECK_USER_STATUS__FAIL = "CHECK_USER_STATUS__FAIL";

const UPDATE_USERDETAILS__REQUEST = "UPDATE_USERDETAILS__REQUEST";
const UPDATE_USERDETAILS__SUCCESS = "UPDATE_USERDETAILS__SUCCESS";
const UPDATE_USERDETAILS__FAIL = "UPDATE_USERDETAILS__FAIL";

const DELETE_USER__REQUEST = "DELETE_USER__REQUEST";
const DELETE_USER__SUCCESS = "DELETE_USER__SUCCESS";
const DELETE_USER__FAIL = "DELETE_USER__FAIL";


const CLEAR__MESSAGES = "CLEAR__MESSAGES";
const CLEAR__ERRORS = "CLEAR__ERRORS";

export {
    REGISTER__REQUEST, REGISTER__SUCCESS, REGISTER__FAIL,
    CHANGE_EMAIL_AT_VERIFICATION,
    REGISTERATION_VERIFICATION__REQUEST, REGISTERATION_VERIFICATION__SUCCESS, REGISTERATION_VERIFICATION__FAIL,
    OTP_VERIFICATION_FAILURE__REQUEST, OTP_VERIFICATION_FAILURE__SUCCESS, OTP_VERIFICATION_FAILURE__FAIL,
    RESEND_OTP__REQUEST, RESEND_OTP__SUCCESS, RESEND_OTP__FAIL,
    LOGIN__REQUEST, LOGIN__SUCCESS, LOGIN__FAIL,
    FORGOT_PASSWORD__REQUEST, FORGOT_PASSWORD__SUCCESS, FORGOT_PASSWORD__FAIL,
    RESET_PASSWORD_VERIFICATION__REQUEST, RESET_PASSWORD_VERIFICATION__SUCCESS, RESET_PASSWORD_VERIFICATION__FAIL,
    RESET_PASSWORD_RESEND_OTP__REQUEST, RESET_PASSWORD_RESEND_OTP__SUCCESS, RESET_PASSWORD_RESEND_OTP__FAIL,
    CHECK_USER_STATUS__REQUEST, CHECK_USER_STATUS__SUCCESS, CHECK_USER_STATUS__FAIL,
    LOGOUT__REQUEST, LOGOUT__SUCCESS, LOGOUT__FAIL,
    UPDATE_USERDETAILS__REQUEST, UPDATE_USERDETAILS__SUCCESS, UPDATE_USERDETAILS__FAIL,
    DELETE_USER__REQUEST, DELETE_USER__SUCCESS, DELETE_USER__FAIL,

    CLEAR__ERRORS, CLEAR__MESSAGES
};